Repository boostcampwm-2022/WEB26-RunWithMe, pull requests merged in 2022-11, with the labels that each got.

#4 프로젝트 초기 설정
  .vscode/settings.json
  client/.eslintrc.js
  client/.gitignore
  client/.prettierrc
  client/README.md
  client/craco.config.ts
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.css
  client/src/App.test.tsx
  client/src/App.tsx
  client/src/index.css
  client/src/index.tsx
  client/src/logo.svg
  client/src/react-app-env.d.ts
  client/src/reportWebVitals.ts
  client/src/setupTests.ts
  client/tsconfig.json
  server/.eslintrc.js
  server/.gitignore
  server/.prettierrc
  server/README.md
  server/nest-cli.json
  server/package-lock.json
  server/package.json
  server/src/app.controller.spec.ts
  server/src/app.controller.ts
  server/src/app.module.ts
  server/src/app.service.ts
  server/src/main.ts
  server/test/app.e2e-spec.ts
  server/test/jest-e2e.json
  server/tsconfig.build.json
  server/tsconfig.json
Labels: structure, backend, frontend

#6 Nest.js 기본 설정
  server/.gitignore
  server/package-lock.json
  server/package.json
  server/prisma/migrations/20221113212653_init/migration.sql
  server/prisma/migrations/migration_lock.toml
  server/prisma/schema.prisma
  server/src/app.controller.spec.ts
  server/src/app.controller.ts
  server/src/app.module.ts
  server/src/app.service.ts
  server/src/main.ts
  server/src/prisma/prisma.module.ts
  server/src/prisma/prisma.service.ts
Labels: backend, settings

#9 FE 추가 설정
  client/.eslintrc.js
  client/.storybook/main.js
  client/.storybook/preview.js
  client/craco.config.ts
  client/package-lock.json
  client/package.json
  client/src/components/Button/Button.stories.tsx
  client/src/components/Button/index.tsx
  client/src/components/Button/styles.ts
  client/src/logo.svg
  client/src/styles/color.ts
  client/src/styles/flex.ts
  client/src/styles/font.ts
  client/tsconfig.json
Labels: structure, frontend

#11 공통 컴포넌트 작성
  client/.eslintrc.js
  client/.gitignore
  client/.storybook/main.js
  client/package-lock.json
  client/package.json
  client/src/assets/icons/arrow_left.svg
  client/src/assets/icons/index.ts
  client/src/assets/icons/more_button.svg
  client/src/assets/icons/plus_button.svg
  client/src/assets/icons/user_circle.svg
  client/src/components/Button/Button.stories.tsx
  client/src/components/Button/Button.styles.ts
  client/src/components/Button/Button.tsx
  client/src/components/DetailLabel/DetailLabel.stories.tsx
  client/src/components/DetailLabel/DetailLabel.tsx
  client/src/components/Header/Header.stories.tsx
  client/src/components/Header/Header.tsx
  client/src/components/Input/Input.stories.tsx
  client/src/components/Input/Input.tsx
  client/src/components/Modal/Modal.stories.tsx
  client/src/components/Modal/Modal.styles.ts
  client/src/components/Modal/Modal.tsx
  client/src/components/MoreButton/MoreButton.stories.tsx
  client/src/components/MoreButton/MoreButton.tsx
  client/src/components/PlusButton/PlusButton.stories.tsx
  client/src/components/PlusButton/PlusButton.tsx
  client/src/styles/flex.ts
Labels: frontend

#21 feat: #12 BE 회원가입 API 구현
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/entities/recruit.entity.ts
  server/src/entities/user.entity.ts
  server/src/user/dto/userDTO.ts
  server/src/user/user.controller.spec.ts
  server/src/user/user.controller.ts
  server/src/user/user.module.ts
  server/src/user/user.service.spec.ts
  server/src/user/user.service.ts
Labels: backend

#23 카카오 지도 API 연동
  client/.gitignore
  client/.storybook/preview-head.html
  client/.storybook/preview.js
  client/public/index.html
  client/src/App.tsx
  client/src/assets/icons/index.ts
  client/src/assets/icons/zoom_in_icon.svg
  client/src/assets/icons/zoom_out_icon.svg
  client/src/components/Map/ViewMap/ViewMap.stories.tsx
  client/src/components/Map/ViewMap/ViewMap.tsx
  client/src/components/Map/ZoomControl/ZoomControl.stories.tsx
  client/src/components/Map/ZoomControl/ZoomControl.tsx
  client/src/hooks/useMap.tsx
  client/src/types/LatLng.ts
  client/src/types/maps/LatLng.d.ts
  client/src/types/maps/Map.d.ts
  client/src/types/maps/MouseEvent.d.ts
  client/src/types/maps/Polyline.d.ts
  client/src/types/maps/RoadviewClient.d.ts
  client/src/types/maps/event.d.ts
Labels: frontend

#24 도커 개발환경 구성
  client/.dockerignore
  client/Dockerfile.dev
  client/docker-compose.yml
  dev.sh
  server/.dockerignore
  server/.gitignore
  server/Dockerfile.dev
  server/docker-compose.yml
  server/package-lock.json
  server/package.json
  server/src/app.controller.ts
  server/src/app.module.ts
  server/src/main.ts
  server/src/user/user.service.ts
Labels: backend

#25 feat: #16 로그인 API 구현
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/auth/auth.controller.spec.ts
  server/src/auth/auth.controller.ts
  server/src/auth/auth.module.ts
  server/src/auth/auth.service.spec.ts
  server/src/auth/auth.service.ts
  server/src/auth/dto/loginDTO.ts
Labels: backend

#26 feat: 회원가입 페이지 퍼블리싱 및 API 연동
  client/package-lock.json
  client/package.json
  client/src/index.tsx
  client/src/pages/SignUp.tsx
Labels: frontend

#28 useInput hooks 작성
  client/src/App.tsx
  client/src/constants/constants.ts
  client/src/hooks/useInput.ts
  client/src/pages/SignUp.styles.ts
  client/src/pages/SignUp.tsx
  client/src/utils/valitationUtils.ts
Labels: frontend

#32 chore: 도커파일 업데이트
  server/docker-compose.yml
Labels: backend, DevOps

#35 feat/loginpage : 로그인페이지 퍼블리싱 및 버그픽스
  client/src/App.tsx
  client/src/pages/Login.styles.ts
  client/src/pages/Login.tsx
  client/src/pages/MainPage.tsx
  client/src/pages/SignUp.styles.ts
  client/src/pages/SignUp.tsx
  client/src/utils/valitationUtils.ts
Labels: frontend

#38 feat: 커스텀 레포지터리 적용
  server/package-lock.json
  server/package.json
  server/src/auth/auth.controller.spec.ts
  server/src/auth/auth.controller.ts
  server/src/auth/auth.module.ts
  server/src/auth/auth.service.spec.ts
  server/src/auth/auth.service.ts
  server/src/auth/dto/login-user.dto.ts
  server/src/auth/dto/loginDTO.ts
  server/src/common/constant/error_message.ts
  server/src/common/decorator/validator.ts
  server/src/common/typeorm/typeorm.decorator.ts
  server/src/common/typeorm/typeorm.module.ts
  server/src/user/dto/create-user.dto.ts
  server/src/user/dto/update-user.dto.ts
  server/src/user/dto/userDTO.ts
  server/src/user/user.controller.spec.ts
  server/src/user/user.controller.ts
  server/src/user/user.module.ts
  server/src/user/user.repository.ts
  server/src/user/user.service.spec.ts
  server/src/user/user.service.ts
Labels: backend

#43 feat: #42 auth guard, redis에 refreshtoken 저장, auth repository 생성
  server/dump.rdb
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/auth/auth.controller.ts
  server/src/auth/auth.module.ts
  server/src/auth/auth.repository.ts
  server/src/auth/auth.service.ts
  server/src/common/guard/auth.guard.ts
  server/src/common/guard/refresh.guard.ts
  server/src/main.ts
  server/src/user/user.service.ts
Labels: backend

#41 SignUp 페이지 오류 수정
  client/src/hooks/useInput.ts
  client/src/pages/Login.tsx
  client/src/pages/SignUp.styles.ts
  client/src/pages/SignUp.tsx
Labels: frontend

#47 코스 / 모집 카드 컴포넌트 구현
  client/src/assets/icons/index.ts
  client/src/assets/icons/location_icon.svg
  client/src/assets/icons/ruler_icon.svg
  client/src/assets/icons/running_icon.svg
  client/src/components/Card/Card.styles.ts
  client/src/components/Card/Card.tsx
  client/src/components/Card/CourseCard/CourseCard.stories.tsx
  client/src/components/Card/CourseCard/CourseCard.tsx
  client/src/components/Card/RecruitCard/RecruitCard.stories.tsx
  client/src/components/Card/RecruitCard/RecruitCard.tsx
  client/src/types/Course.ts
  client/src/types/Recruit.ts
  client/src/utils/stringtils.ts
Labels: frontend

#40 PaceInput 컴포넌트 작성
  client/src/components/Input/Input.stories.tsx
  client/src/components/Input/Input.style.ts
  client/src/components/Input/Input.tsx
  client/src/components/Input/PaceInput/PaceInput.stories.tsx
  client/src/components/Input/PaceInput/PaceInput.tsx
  client/src/constants/errorMessage.ts
  client/src/constants/placeholder.ts
  client/src/hooks/usePaceInput.ts
  client/src/pages/Login.tsx
  client/src/pages/SignUp.tsx
Labels: frontend

#48 코스 등록 페이지 기능 구현
  client/src/App.tsx
  client/src/assets/icons/index.ts
  client/src/assets/icons/lock_icon.svg
  client/src/assets/icons/undo_icon.svg
  client/src/assets/icons/unlock_icon.svg
  client/src/components/Button/Button.tsx
  client/src/components/Map/ViewMap/ViewMap.stories.tsx
  client/src/components/MapControl/LockButton/LockButton.stories.tsx
  client/src/components/MapControl/LockButton/LockButton.tsx
  client/src/components/MapControl/MapControl.styles.ts
  client/src/components/MapControl/UndoButton/UndoButton.stories.tsx
  client/src/components/MapControl/UndoButton/UndoButton.tsx
  client/src/components/MapControl/ZoomControl/ZoomControl.stories.tsx
  client/src/components/MapControl/ZoomControl/ZoomControl.tsx
  client/src/constants/placeholder.ts
  client/src/hooks/useMap.tsx
  client/src/hooks/useWriteMap.tsx
  client/src/hooks/useZoomControl.ts
  client/src/pages/NewCourse/NewCourse.tsx
  client/src/types/MapControlProps.ts
  client/src/types/MapProps.ts
Labels: frontend

#49 Feat/silentlogin
  client/craco.config.ts
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/atoms/userState.tsx
  client/src/constants/time.ts
  client/src/index.tsx
  client/src/pages/Login.tsx
  client/tsconfig.json
  dump.rdb
  server/dump.rdb
  server/src/auth/auth.controller.ts
  server/src/common/guard/auth.guard.ts
  server/src/common/guard/refresh.guard.ts
  server/src/main.ts
Labels: frontend

#50 feat: class-validator & class-transformer 적용
  server/src/common/decorator/id.validator.ts
  server/src/common/decorator/index.ts
  server/src/common/decorator/pw.validator.ts
  server/src/common/decorator/validator.ts
  server/src/main.ts
  server/src/user/dto/create-user.dto.ts
  server/src/user/user.controller.ts
Labels: backend

#54 feat: #52 아이디 중복체크 API
  server/src/user/dto/check-user.dto.ts
  server/src/user/user.controller.ts
  server/src/user/user.service.ts
Labels: backend

#67 전체 모집목록 조회&등록 API 구현 (Recruit)
  server/src/common/type/raw-recruit-data.ts
  server/src/entities/course.entity.ts
  server/src/entities/recruit.entity.ts
  server/src/entities/user.entity.ts
  server/src/entities/user_recruit.entity.ts
  server/src/recruit/dto/create-recruit.dto.ts
  server/src/recruit/dto/join-recruit.dto.ts
  server/src/recruit/recruit.controller.ts
  server/src/recruit/recruit.repository.ts
  server/src/recruit/recruit.service.ts
Labels: backend

#76 feat: http 요청 custom hooks 작성
  client/src/App.tsx
  client/src/hooks/http/useAxios.ts
  client/src/hooks/http/useHttpGet.ts
  client/src/hooks/http/useHttpPatch.ts
  client/src/hooks/http/useHttpPost.ts
  client/src/pages/Login.tsx
  client/src/pages/RecruitDetail.tsx
  client/src/pages/SignUp.tsx
Labels: frontend

#81 온오프 필터 구현
  client/src/assets/icons/location_icon.svg
  client/src/components/Filter/Filter.stories.tsx
  client/src/components/FilterBar/FilterBar.tsx
  client/src/components/OnOffFilter/OnOffFilter.stories.tsx
  client/src/components/OnOffFilter/OnOffFilter.tsx
  client/src/components/SelectFilter/SelectFilter.stories.tsx
  client/src/components/SelectFilter/SelectFilter.style.ts
  client/src/components/SelectFilter/SelectFilter.tsx
  client/src/hooks/useFilter.ts
  client/src/hooks/useFilter.tsx
  client/src/hooks/useOnOffFilter.ts
  client/src/pages/Courses.tsx
Labels: frontend

#90 feat 코스 등록 API 연동 / 코스 정보에 hName 저장하도록 수정
  client/src/hooks/useLocalAPI.ts
  client/src/pages/NewCourse/NewCourse.styles.ts
  client/src/pages/NewCourse/NewCourse.tsx
  client/src/types/Region.ts
  client/src/utils/mapUtils.ts
  client/src/utils/valitationUtils.ts
  server/src/course/dto/create-course.dto.ts
  server/src/entities/course.entity.ts
Labels: backend, frontend

#94 refactor: #93 RecruitCard 최신화
  client/src/assets/icons/index.ts
  client/src/assets/icons/ruler_icon.svg
  client/src/assets/icons/running_icon.svg
  client/src/assets/icons/user_icon.svg
  client/src/components/Card/Card.styles.ts
  client/src/components/Card/CourseCard/CourseCard.stories.tsx
  client/src/components/Card/CourseCard/CourseCard.tsx
  client/src/components/Card/RecruitCard/RecruitCard.stories.tsx
  client/src/components/Card/RecruitCard/RecruitCard.tsx
  client/src/types/Course.ts
  client/src/types/Recruit.ts
  client/src/types/hDong.ts
Labels: frontend

#100 모집 목록 페이지 퍼블리싱 완료
  client/src/App.tsx
  client/src/assets/icons/clock_icon.svg
  client/src/assets/icons/index.ts
  client/src/components/Card/RecruitCard/RecruitCard.tsx
  client/src/components/OnOffFilter/OnOffFilter.tsx
  client/src/components/SearchBar/SearchBar.tsx
  client/src/components/SelectFilter/SelectFilter.tsx
  client/src/hooks/http/useHttpGet.ts
  client/src/index.tsx
  client/src/pages/Courses.tsx
  client/src/pages/MainPage.tsx
  client/src/pages/Recruits.tsx
  client/src/pages/SignUp.styles.ts
  client/src/utils/stringtils.ts
  dump.rdb
  server/dump.rdb
Labels: frontend

#96 feat: #51 주소 검색 API 프로토타입
  client/src/assets/icons/delete_icon.svg
  client/src/assets/icons/index.ts
  client/src/components/AddressList/AddressList.styles.ts
  client/src/components/AddressList/AddressList.tsx
  client/src/components/Input/Input.style.ts
  client/src/components/Input/Input.tsx
  client/src/components/ResetButton/ResetButton.tsx
  client/src/pages/SignUp.tsx
  client/src/types/Course.ts
  client/src/utils/valitationUtils.ts
Labels: frontend

#101 feat: 모집 상세 페이지 지도위에 코스 나타내기 성공
  client/src/hooks/useShowMap.tsx
  client/src/hooks/useWriteMap.tsx
  client/src/pages/RecruitDetail.tsx
  client/src/types/MapProps.ts
Labels: frontend

#103 feat: 코스 검색/필터 API 구현
  server/src/common/type/raw-course-data.ts
  server/src/course/course.controller.ts
  server/src/course/course.repository.ts
  server/src/course/course.service.ts
  server/src/course/dto/get-course.dto.ts
Labels: backend

#111 refactor: time->hour로 파라미터 변경 작업 및 응답에서 course.userId가 누락되어 있던 문제 수정
  server/src/common/type/raw-recruit-data.ts
  server/src/common/utils/plainToGetRecruitDto.ts
  server/src/recruit/dto/get-recruit.dto.ts
  server/src/recruit/recruit.controller.ts
  server/src/recruit/recruit.repository.ts
  server/src/recruit/recruit.service.ts
Labels: backend, refactor

#113 feat: 주소 검색 컴포넌트 구현
  client/src/components/AddressList/AddressList.tsx
  client/src/components/Input/AddressSearchInput/AddressSearchInput.tsx
  client/src/components/Input/AddressSearchInput/Input.stories.tsx
  client/src/components/Input/Input.stories.tsx
  client/src/components/Input/Input.tsx
  client/src/components/Modal/Modal.stories.tsx
  client/src/components/SignUpForm/SignUpForm.tsx
  client/src/constants/placeholder.ts
  client/src/hooks/useLocalAPI.ts
  client/src/pages/Login.tsx
  client/src/pages/NewCourse/NewCourse.tsx
  client/src/pages/SignUp.styles.ts
  client/src/pages/SignUp.tsx
  client/src/types/Address.ts
  client/src/types/LocalAPIType.ts
  client/src/utils/addressUtils.ts
  client/src/utils/validationUtils.ts
Labels: frontend

#116 필터 컴포넌트 리팩토링
  client/src/components/SelectFilter/SelectFilter.stories.tsx
  client/src/components/SelectFilter/SelectFilter.tsx
  client/src/hooks/useFilter.ts
  client/src/pages/Courses.tsx
  client/src/pages/Recruits.tsx
  client/src/types/FilterOption.ts
Labels: frontend

#120 feat: h_dong , recruit, course 엔터티 수정 및 응답에서 h_code를 name으로 바꿔서 내려주게끔 수정
  server/src/common/type/course-data.ts
  server/src/common/type/raw-recruit-data.ts
  server/src/common/utils/plainToGetRecruitDto.ts
  server/src/course/course.repository.ts
  server/src/course/course.service.ts
  server/src/course/dto/create-course.dto.ts
  server/src/entities/course.entity.ts
  server/src/entities/h_dong.entity.ts
  server/src/entities/recruit.entity.ts
  server/src/recruit/dto/create-recruit.dto.ts
  server/src/recruit/recruit.controller.ts
  server/src/recruit/recruit.module.ts
  server/src/recruit/recruit.repository.ts
  server/src/recruit/recruit.service.ts
Labels: backend, refactor

#114 feat 클라이언트 유저 권한 분기
  client/src/components/Header/Header.stories.tsx
  client/src/components/Header/Header.tsx
  client/src/components/PlusButton/PlusButton.tsx
  client/src/hooks/useAuth.ts
  client/src/pages/CourseDetail.tsx
  client/src/pages/Login.tsx
  client/src/pages/NewCourse/NewCourse.tsx
  client/src/pages/RecruitDetail.tsx
  client/src/pages/SignUp.tsx
Labels: frontend

#123 feat: 모집 정보 입력 모달
  client/src/components/Input/MaxPplInput/MaxPplInput.tsx
  client/src/components/Input/StartTimeInput/StartTimeInput.strories.tsx
  client/src/components/Input/StartTimeInput/StartTimeInput.tsx
  client/src/components/Modal/Modal.styles.ts
  client/src/constants/errorMessage.ts
  client/src/constants/placeholder.ts
  client/src/hooks/useMaxPplInput.ts
  client/src/hooks/useStartTimeInput.ts
  client/src/pages/CourseDetail.tsx
  client/src/styles/flex.ts
  client/src/utils/validationUtils.ts
Labels: frontend

#134 Refactor/jwt
  server/src/app.module.ts
  server/src/auth/auth.module.ts
  server/src/auth/auth.service.ts
  server/src/common/guards/access.guard.ts
  server/src/common/guards/refresh.guard.ts
  server/src/common/modules/custom-jwt/custom-jwt.module.ts
  server/src/common/modules/custom-jwt/custom-jwt.service.ts
  server/src/common/repositories/user_recruit.repository.ts
  server/src/recruit/dto/request/create-recruit.request.ts
  server/src/recruit/dto/request/get-recruit.request.ts
  server/src/recruit/dto/request/join-recruit.request.ts
  server/src/recruit/recruit.controller.ts
  server/src/recruit/recruit.module.ts
  server/src/recruit/recruit.service.ts
  server/src/user/user.module.ts
  server/src/user_recruit.repository.ts
Labels: backend, refactor

#132 refactor: fe 구조/hooks 개선
  client/.storybook/main.js
  client/src/App.tsx
  client/src/components/Button/Button.stories.tsx
  client/src/components/DetailLabel/DetailLabel.stories.tsx
  client/src/components/FilterBar/FilterBar.stories.tsx
  client/src/components/Header/Header.stories.tsx
  client/src/components/Input/AddressSearchInput/Input.stories.tsx
  client/src/components/Input/PaceInput/PaceInput.stories.tsx
  client/src/components/Input/StartTimeInput/StartTimeInput.stories.tsx
  client/src/components/MapControl/MapControl.styles.ts
  client/src/components/MapControl/PlaceSearch/PlaceSearch.stories.tsx
  client/src/components/MapControl/PlaceSearch/PlaceSearch.styles.ts
  client/src/components/Modal/Modal.stories.tsx
  client/src/components/MoreButton/MoreButton.stories.tsx
  client/src/components/OnOffFilter/OnOffFilter.stories.tsx
  client/src/components/PlusButton/PlusButton.stories.tsx
  client/src/components/ResetButton/ResetButton.stories.tsx
  client/src/components/SearchBar/SearchBar.stories.tsx
  client/src/components/SelectFilter/SelectFilter.stories.tsx
  client/src/components/SignUpForm/SignUpForm.tsx
  client/src/hooks/useInput.ts
  client/src/hooks/useLocalAPI.ts
  client/src/hooks/usePlaceSearch.ts
  client/src/hooks/useWriteMap.tsx
  client/src/pages/CourseDetail/CourseDetail.styles.ts
  client/src/pages/CourseDetail/CourseDetail.tsx
  client/src/pages/Courses/Courses.tsx
  client/src/pages/Login/Login.styles.ts
  client/src/pages/Login/Login.tsx
  client/src/pages/MainPage/MainPage.tsx
  client/src/pages/RecruitDetail/RecruitDetail.tsx
  client/src/pages/Recruits/Recruits.tsx
  client/src/pages/SignUp/SignUp.styles.ts
  client/src/pages/SignUp/SignUp.tsx
  client/src/types/MapControlProps.ts
Labels: frontend, refactor

#138 목데이터 페이지 + 코스 목록 페이지 구현
  .gitignore
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/Card/Card.styles.ts
  client/src/constants/hdongs.ts
  client/src/pages/Courses/Courses.tsx
  client/src/pages/MainPage/MainPage.tsx
  client/src/pages/Mock.tsx
  client/src/pages/Recruits/Recruits.tsx
  package-lock.json
  server/src/app.module.ts
Labels: frontend

#150 refactor: BE 리팩토링 (Recruit) & ResponseEntity 추가
  server/package-lock.json
  server/src/common/interceptors/http-request/http-request-body.interceptor.ts
  server/src/common/repositories/recruit.repository.ts
  server/src/common/response/response.entity.ts
  server/src/common/response/response.status.ts
  server/src/course/course.controller.ts
  server/src/course/course.service.ts
  server/src/course/dto/request/create-course.dto.ts
  server/src/course/dto/request/get-course.dto.ts
  server/src/course/dto/response/get-one.response.ts
  server/src/recruit/dto/request/create.request.ts
  server/src/recruit/dto/request/get-many.request.ts
  server/src/recruit/dto/response/create.response.ts
  server/src/recruit/dto/response/get-many.response.ts
  server/src/recruit/dto/response/get-one.response.ts
  server/src/recruit/recruit.controller.ts
  server/src/recruit/recruit.service.ts
Labels: backend, refactor
