Repository boostcampwm-2022/WEB26-RunWithMe, pull requests merged in 2022-12, with the labels that each got.

#154 Feat/mockdata recruit
  client/src/App.tsx
  client/src/components/Card/RecruitCard/RecruitCard.tsx
  client/src/pages/MainPage/MainPage.tsx
  client/src/pages/MockCourses.tsx
  client/src/pages/MockRecruits.tsx
  server/src/common/repositories/course.repository.ts
  server/src/course/course.controller.ts
  server/src/course/course.service.ts
Labels: frontend

#166 feat: 확인 모달창 -> 모집 참여, 모집 생성, 코스 생성
  client/src/pages/CourseDetail/CourseDetail.tsx
  client/src/pages/NewCourse/NewCourse.tsx
  client/src/pages/RecruitDetail/RecruitDetail.tsx
  server/src/course/response/get-one.response.ts
Labels: frontend

#168 Refactor : be course response dto
  server/src/common/entities/course.entity.ts
  server/src/common/repositories/course.repository.ts
  server/src/common/repositories/recruit.repository.ts
  server/src/common/types/course-data.ts
  server/src/common/types/raw-recruit-data.ts
  server/src/common/utils/plainToGetRecruitDto.ts
  server/src/course/course.controller.ts
  server/src/course/course.service.ts
  server/src/course/dto/request/create-course.dto.ts
  server/src/course/dto/response/create.response.ts
  server/src/course/dto/response/get-many.response.ts
  server/src/course/dto/response/get-one.response.ts
  server/src/recruit/recruit.controller.ts
Labels: backend

#176 v0.2
  client/src/components/Card/Card.styles.ts
  client/src/components/Card/Card.tsx
  client/src/components/Card/CourseCard/CourseCard.stories.tsx
  client/src/components/Card/CourseCard/CourseCard.tsx
  client/src/components/Card/RecruitCard/RecruitCard.stories.tsx
  client/src/components/Card/RecruitCard/RecruitCard.tsx
  client/src/components/Card/RecruitTextCard/RecruitTextCard.tsx
  client/src/components/DetailLabel/DetailLabel.tsx
  client/src/hooks/useCardMap.tsx
  client/src/pages/Courses/Courses.tsx
  client/src/pages/MockRecruits.tsx
  client/src/pages/NewCourse/NewCourse.tsx
  client/src/pages/Recruits/Recruits.tsx
  client/src/types/Course.ts
  client/src/utils/pathUtils.ts
  server/src/course/course.service.ts
  server/src/recruit/recruit.service.ts
Labels: release

#179 hotfix: 컴포넌트 우선순위 추가
  client/src/App.tsx
  client/src/components/Modal/Modal.styles.ts
  client/src/components/PlusButton/PlusButton.tsx
  client/src/pages/CourseDetail/CourseDetail.tsx
  client/src/pages/Mypage/Mypage.tsx
  server/src/course/course.service.ts
Labels: frontend

#190 test: e2e 테스트 작성
  client/src/pages/RecruitDetail/RecruitDetail.tsx
  server/src/app.module.ts
  server/src/auth/auth.controller.ts
  server/src/common/repositories/user_recruit.repository.ts
  server/src/course/course.controller.ts
  server/src/user/user.service.ts
  server/test/app.e2e-spec.ts
  server/test/config/query.ts
  server/test/jest-e2e.json
Labels: backend

#180 마이페이지 퍼블리싱
  client/public/index.html
  client/src/App.tsx
  client/src/components/Header/Header.tsx
  client/src/constants/myPageOptions.ts
  client/src/pages/Main/MainPage.styles.ts
  client/src/pages/MyPage/MyPage.styles.ts
  client/src/pages/MyPage/MyPage.tsx
  client/src/pages/MyPage/MyPageCourses.tsx
  client/src/pages/MyPage/MyPageProfile.tsx
  client/src/pages/MyPage/MyPageRecruits.tsx
  client/src/pages/MyPage/MyPageTypes.ts
  client/src/pages/Mypage/Mypage.tsx
  client/src/pages/RecruitDetail/RecruitDetail.tsx
  client/tsconfig.json
Labels: frontend

#202 유저 코스 DTO 변환 오류 및 API 수정으로 인한 버그 수정
  server/.gitignore
  server/package.json
  server/src/auth/auth.controller.ts
  server/src/common/repositories/course.repository.ts
  server/src/course/course.controller.ts
  server/src/course/course.service.ts
  server/src/course/dto/response/get-course.response.ts
  server/src/course/dto/response/get-courses.response.ts
  server/src/user/dto/request/check-user.request.ts
  server/src/user/dto/request/create-user.request.ts
  server/src/user/dto/request/update-user.request.ts
  server/src/user/user.controller.ts
  server/src/user/user.module.ts
  server/src/user/user.service.ts
  server/test/app.e2e-spec.ts
Labels: backend

#204 refactor: #203 webpack -> vite
  client/.storybook/main.js
  client/.storybook/preview-head.html
  client/craco.config.ts
  client/index.html
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/hooks/http/useAxios.ts
  client/src/hooks/useLocalAPI.ts
  client/src/vite-env.d.ts
  client/tsconfig.json
  client/vite.config.ts
Labels: frontend

#210 마이페이지 구현
  client/package-lock.json
  client/src/hooks/queries/useMyCoursesQuery.ts
  client/src/hooks/queries/useMyProfileQuery.ts
  client/src/hooks/queries/useMyRecruitsQuery.ts
  client/src/pages/MockRecruits.tsx
  client/src/pages/MyPage/MyPageCourses.tsx
  client/src/pages/MyPage/MyPageProfile.tsx
  client/src/pages/MyPage/MyPageRecruits.tsx
  client/src/types/Profile.ts
  server/src/app.module.ts
  server/src/common/repositories/course.repository.ts
  server/src/common/repositories/recruit.repository.ts
  server/src/common/repositories/user.repository.ts
  server/src/user/dto/response/get-profile.response.ts
  server/src/user/user.controller.ts
  server/src/user/user.module.ts
  server/src/user/user.service.ts
Labels: backend, frontend

#213 feat: user 엔티티 추가사항 반영 및 user와 hCode 엔티티간 관계 설정되어 있지 않던 이슈 수정
  server/src/common/entities/h_dong.entity.ts
  server/src/common/entities/user.entity.ts
  server/src/common/transformer/boolean.transformer.ts
Labels: backend

#219 마이페이지 개선
  client/package-lock.json
  client/package.json
  client/src/components/Card/Card.styles.ts
  client/src/components/Card/RecruitCard/RecruitCard.tsx
  client/src/components/Card/RecruitTextCard/RecruitTextCard.tsx
  client/src/constants/time.ts
  client/src/pages/MyPage/MyPage.styles.ts
  client/src/pages/MyPage/MyPageRecruits.tsx
  client/src/pages/RecruitDetail/RecruitDetail.tsx
  client/src/utils/cardUtils.ts
Labels: frontend

#226 feat: 채팅 서버 ver 1.0.0 구현
  chat-server/.eslintrc.js
  chat-server/.gitignore
  chat-server/.prettierrc
  chat-server/README.md
  chat-server/nest-cli.json
  chat-server/package-lock.json
  chat-server/package.json
  chat-server/src/common/entities/chat.entity.ts
  chat-server/src/main.ts
  chat-server/src/socket.gateway.ts
  chat-server/src/socket.module.ts
  chat-server/src/socket.service.ts
  chat-server/test/app.e2e-spec.ts
  chat-server/test/jest-e2e.json
  chat-server/tsconfig.build.json
  chat-server/tsconfig.json
Labels: backend

#233 테스트 코드 리팩토링 + 유저 테스트 코드 추가
  server/package.json
  server/test/app.e2e-spec.ts
  server/test/data/expectedData.ts
  server/test/data/mockData.ts
  server/test/data/requestData.ts
  server/test/helpers/users.ts
  server/test/types/courseResponse.ts
  server/test/types/coursesResponse.ts
Labels: backend

#234 Feat/chat page
  .gitignore
  chat-server/src/common/schemas/chat.schema.ts
  chat-server/src/socket.gateway.ts
  chat-server/src/socket.service.ts
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/assets/icons/index.ts
  client/src/assets/icons/send_icon.svg
  client/src/components/Chat/Chat.tsx
  client/src/components/Chat/ChatInput/ChatInput.tsx
  client/src/components/Chat/ChatItem/ChatItem.tsx
  client/src/components/Chat/ChatList/ChatList.tsx
  client/src/components/Chat/ChatRoomSummary/ChatRoomSummary.tsx
  client/src/components/FilterBar/FilterBar.tsx
  client/src/components/RecruitContent/RecruitContent.styles.ts
  client/src/components/RecruitContent/RecruitContent.tsx
  client/src/components/commons/ChatButton/ChatButton.tsx
  client/src/constants/socketEvents.ts
  client/src/constants/styles.ts
  client/src/index.tsx
  client/src/pages/Chat/ChatPage.tsx
  client/src/pages/index.tsx
  client/src/styles/color.ts
  client/src/types/Chat.ts
  package.json
Labels: frontend

#236 chat-server 도커파일 추가
  .vscode/tasks.json
  chat-server/.gitignore
  chat-server/Dockerfile
  chat-server/docker-compose.yml
  docker-compose.yml
  noti-server/docker-compose.yml
  server/docker-compose.yml
Labels: DevOps

#241 feat: chat server ver 2.1.0
  chat-server/package-lock.json
  chat-server/package.json
  chat-server/src/common/entities/chat.entity.ts
  chat-server/src/common/schemas/chat.schema.ts
  chat-server/src/main.ts
  chat-server/src/queue-manager/manager.module.ts
  chat-server/src/queue-manager/manager.service.ts
  chat-server/src/socket.controller.ts
  chat-server/src/socket.gateway.ts
  chat-server/src/socket.module.ts
  chat-server/src/socket.service.ts
  client/src/components/Chat/Chat.tsx
  client/src/components/Chat/ChatList/ChatList.tsx
  client/src/constants/socketEvents.ts
  client/src/hooks/queries/useChatQuery.ts
  noti-server/src/app.service.ts
  server/src/recruit/recruit.controller.ts
  server/src/recruit/recruit.module.ts
  server/src/user/user.module.ts
  server/src/user/user.service.ts
Labels: backend

#247 fix: 채팅 서버 고도화 v2.2.1
  chat-server/package-lock.json
  chat-server/package.json
  chat-server/src/common/entities/chat.entity.ts
  chat-server/src/common/modules/queue-map/queue-map.module.ts
  chat-server/src/common/modules/queue-map/queue-map.service.ts
  chat-server/src/common/modules/socket-map/socket-map.module.ts
  chat-server/src/common/modules/socket-map/socket-map.service.ts
  chat-server/src/common/modules/unread-map/unread-map.module.ts
  chat-server/src/common/modules/unread-map/unread-map.service.ts
  chat-server/src/common/schemas/chat.schema.ts
  chat-server/src/main.ts
  chat-server/src/queue-manager/manager.module.ts
  chat-server/src/queue-manager/manager.service.ts
  chat-server/src/socket.controller.ts
  chat-server/src/socket.gateway.ts
  chat-server/src/socket.module.ts
  chat-server/src/socket.service.ts
  client/src/components/Chat/Chat.tsx
  client/src/components/Chat/ChatList/ChatList.tsx
  client/src/constants/socketEvents.ts
  client/src/hooks/queries/useChatQuery.ts
  client/src/pages/ChatTest.tsx
  server/src/recruit/recruit.controller.ts
  server/src/recruit/recruit.module.ts
  server/src/user/user.module.ts
  server/src/user/user.service.ts
Labels: backend

#248 Revert "fix: 채팅 서버 고도화 v2.2.1"
  chat-server/package-lock.json
  chat-server/package.json
  chat-server/src/common/entities/chat.entity.ts
  chat-server/src/common/modules/queue-map/queue-map.module.ts
  chat-server/src/common/modules/queue-map/queue-map.service.ts
  chat-server/src/common/modules/socket-map/socket-map.module.ts
  chat-server/src/common/modules/socket-map/socket-map.service.ts
  chat-server/src/common/modules/unread-map/unread-map.module.ts
  chat-server/src/common/modules/unread-map/unread-map.service.ts
  chat-server/src/common/schemas/chat.schema.ts
  chat-server/src/main.ts
  chat-server/src/queue-manager/manager.module.ts
  chat-server/src/queue-manager/manager.service.ts
  chat-server/src/socket.controller.ts
  chat-server/src/socket.gateway.ts
  chat-server/src/socket.module.ts
  chat-server/src/socket.service.ts
  client/src/components/Chat/Chat.tsx
  client/src/components/Chat/ChatList/ChatList.tsx
  client/src/constants/socketEvents.ts
  client/src/hooks/queries/useChatQuery.ts
  client/src/pages/ChatTest.tsx
  server/src/recruit/recruit.controller.ts
  server/src/recruit/recruit.module.ts
  server/src/user/user.module.ts
  server/src/user/user.service.ts
Labels: backend

#251 fix: 채팅 서버 고도화 v2.3.0
  chat-server/src/common/modules/queue-map/queue-map.module.ts
  chat-server/src/common/modules/queue-map/queue-map.service.ts
  chat-server/src/common/modules/socket-map/socket-map.module.ts
  chat-server/src/common/modules/socket-map/socket-map.service.ts
  chat-server/src/common/modules/unread-map/unread-map.module.ts
  chat-server/src/common/modules/unread-map/unread-map.service.ts
  chat-server/src/common/types/get-many.type.ts
  chat-server/src/common/types/get-one.type.ts
  chat-server/src/common/types/history.type.ts
  chat-server/src/common/types/index.ts
  chat-server/src/main.ts
  chat-server/src/queue-manager/manager.module.ts
  chat-server/src/queue-manager/manager.service.ts
  chat-server/src/socket.controller.ts
  chat-server/src/socket.gateway.ts
  chat-server/src/socket.module.ts
  chat-server/src/socket.service.ts
  client/src/components/Chat/Chat.tsx
  client/src/components/Chat/ChatList/ChatList.tsx
  client/src/components/Chat/ChatRoomSummary/ChatRoomSummary.tsx
  client/src/components/RecruitContent/RecruitContent.tsx
  client/src/components/commons/ChatButton/ChatButton.tsx
  client/src/constants/socketEvents.ts
  client/src/hooks/queries/useChatQuery.ts
  client/src/types/RecruitDetail.ts
  server/src/recruit/dto/response/get-recruit.response.ts
  server/src/recruit/recruit.controller.ts
  server/src/recruit/recruit.module.ts
  server/src/user/user.module.ts
  server/src/user/user.service.ts
Labels: backend

#253 feat: consumer 분리
  .DS_Store
  .gitignore
  noti-server/src/app.controller.ts
  noti-server/src/app.module.ts
  noti-worker-delayed/.eslintrc.js
  noti-worker-delayed/.gitignore
  noti-worker-delayed/.prettierrc
  noti-worker-delayed/README.md
  noti-worker-delayed/nest-cli.json
  noti-worker-delayed/package-lock.json
  noti-worker-delayed/package.json
  noti-worker-delayed/src/app.consumer.ts
  noti-worker-delayed/src/app.module.ts
  noti-worker-delayed/src/common/templates/cancel.hbs
  noti-worker-delayed/src/common/templates/recruit.hbs
  noti-worker-delayed/src/common/templates/signup.hbs
  noti-worker-delayed/src/mail/mail.module.ts
  noti-worker-delayed/src/mail/mail.service.ts
  noti-worker-delayed/src/main.ts
  noti-worker-delayed/tsconfig.build.json
  noti-worker-delayed/tsconfig.json
  noti-worker-immediate/.eslintrc.js
  noti-worker-immediate/.gitignore
  noti-worker-immediate/.prettierrc
  noti-worker-immediate/README.md
  noti-worker-immediate/nest-cli.json
  noti-worker-immediate/package-lock.json
  noti-worker-immediate/package.json
  noti-worker-immediate/src/app.consumer.ts
  noti-worker-immediate/src/app.module.ts
  noti-worker-immediate/src/common/templates/cancel.hbs
  noti-worker-immediate/src/common/templates/recruit.hbs
  noti-worker-immediate/src/common/templates/signup.hbs
  noti-worker-immediate/src/mail/mail.module.ts
  noti-worker-immediate/src/mail/mail.service.ts
  noti-worker-immediate/src/main.ts
  noti-worker-immediate/tsconfig.build.json
  noti-worker-immediate/tsconfig.json
Labels: backend
